
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public final class AdminMenu extends javax.swing.JPanel {

    /**
     * Creates new form AdminMenu
     */
    private DefaultTableModel model;
    private TableRowSorter<DefaultTableModel> sorter;
    
    public AdminMenu() {
        initComponents();
        initTable();
        loadDataUser();
        setupSearch();
        
    }
        
        
     
   private void initTable() {
    // Override isCellEditable agar SELALU false untuk semua kolom
    model = new DefaultTableModel(
        new Object[]{"ID User", "Username", "Password", "Role"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Mengunci semua sel tabel agar tidak bisa diketik
        }
    };
    
    jTable1.setModel(model);
    sorter = new TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);
    
    // Opsional: Agar saat baris diklik tampilannya lebih jelas
    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
}
   

    private void setupSearch() {
        Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filterData(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filterData(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filterData(); }
        });
    }

    private void filterData() {
        String keyword = Search.getText().trim();
        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));
        }
    }

    
    public void loadDataUser() {
        try (Connection conn = koneksi.getConnection();
             java.sql.Statement stm = conn.createStatement();
             java.sql.ResultSet rs = stm.executeQuery("SELECT * FROM user")) {

            model.setRowCount(0); // Hapus data lama

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_user"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("role")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        b_edit = new javax.swing.JButton();
        B_hapus = new javax.swing.JButton();
        B_Refresh = new javax.swing.JButton();
        Search = new javax.swing.JTextField();

        setBackground(new java.awt.Color(39, 174, 96));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_user", "Username", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        b_edit.setText("Edit");
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });

        B_hapus.setText("Hapus");
        B_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_hapusActionPerformed(evt);
            }
        });

        B_Refresh.setText("Refresh");
        B_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RefreshActionPerformed(evt);
            }
        });

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Refresh)
                .addGap(33, 33, 33))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(b_edit)
                    .addComponent(B_hapus)
                    .addComponent(B_Refresh)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Ketika tombol "Tambah" diklik
    Tambah tambahFrame = new Tambah();
    tambahFrame.setVisible(true);
    tambahFrame.setLocationRelativeTo(null); // agar muncul di tengah layar
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed
                                    
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        // Ambil ID dari kolom pertama tabel
        String id_user = jTable1.getValueAt(selectedRow, 0).toString();

        // Panggil frame EditUser dengan ID tersebut
        EditUser editForm = new EditUser(id_user);
        editForm.setVisible(true);
        editForm.setLocationRelativeTo(null); // tampil di tengah layar
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit terlebih dahulu!");
    }


    }//GEN-LAST:event_b_editActionPerformed

    private void B_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_hapusActionPerformed
        int baris = jTable1.getSelectedRow(); // tabelUser = JTable kamu
        if (baris != -1) { // Pastikan ada baris yang dipilih
             String id = jTable1.getValueAt(baris, 0).toString(); // ambil id_user dari kolom pertama
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data dengan ID: " + id + " ?", 
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = koneksi.getConnection(); // panggil class koneksi kamu
                String sql = "DELETE FROM user WHERE id_user = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, id);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus terlebih dahulu!");
    }
// TODO add your handling code here:
    }//GEN-LAST:event_B_hapusActionPerformed

    private void B_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RefreshActionPerformed
     loadDataUser();
     JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
    
    }//GEN-LAST:event_B_RefreshActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
                                     
        filterData();
    

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Refresh;
    private javax.swing.JButton B_hapus;
    private javax.swing.JTextField Search;
    private javax.swing.JButton b_edit;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}