/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;

public class DataProduk extends javax.swing.JPanel {

    private DefaultTableModel model;
    private TableRowSorter<DefaultTableModel> sorter;

    public DataProduk() {
        initComponents();
        initTable();
        loadDataProduk();
        setupSearchFilter();
    }
    
    private void initTable() {
    // Menambahkan Override isCellEditable agar semua sel terkunci
    model = new DefaultTableModel(
        new Object[]{"ID Barang", "Nama Barang", "ID Kategori", "Harga Beli", "Harga Jual", "Stok", "Satuan", "Diskon"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Mengembalikan false agar pengguna tidak bisa mengedit isi tabel
            return false;
        }
    };
    
    jTable1.setModel(model);
    sorter = new TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);
    }
    
   private void setupSearchFilter() {
        Search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filterData(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filterData(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filterData(); }
        });
    }
        private void filterData() {
        String keyword = Search.getText().trim();
        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));
        }
    }

      
        public void loadDataProduk() {
            try (Connection conn = koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery("SELECT * FROM barang")) {

                model.setRowCount(0);
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_barang"),
                        rs.getString("nama_barang"),
                        rs.getString("id_kategori"),
                        rs.getString("harga_beli"),
                        rs.getString("harga_jual"),
                        rs.getString("stok"),
                        rs.getString("satuan"),
                        rs.getString("diskon")
                    });
                }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B_hapus = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        B_Refresh = new javax.swing.JButton();
        B_tambah = new javax.swing.JButton();
        b_edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(39, 174, 96));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_barang", "Nama barang", "id_kategori", "Harga beli", "Harga jual", "Stok", "Satuan", "Diskon"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        B_hapus.setText("Hapus");
        B_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_hapusActionPerformed(evt);
            }
        });

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        B_Refresh.setText("Refresh");
        B_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RefreshActionPerformed(evt);
            }
        });

        B_tambah.setText("Tambah");
        B_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_tambahActionPerformed(evt);
            }
        });

        b_edit.setText("Edit");
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(B_tambah)
                .addGap(18, 18, 18)
                .addComponent(B_hapus)
                .addGap(18, 18, 18)
                .addComponent(b_edit)
                .addGap(18, 18, 18)
                .addComponent(B_Refresh))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_tambah)
                    .addComponent(B_hapus)
                    .addComponent(b_edit)
                    .addComponent(B_Refresh))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void B_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_tambahActionPerformed
        // Ketika tombol "Tambah" diklik
        TambahProduk tambahFrame = new TambahProduk();
        tambahFrame.setVisible(true);
        tambahFrame.setLocationRelativeTo(null); // agar muncul di tengah layar
        // TODO add your handling code here:
    }//GEN-LAST:event_B_tambahActionPerformed

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // Ambil ID dari kolom pertama tabel
            String id_barang = jTable1.getValueAt(selectedRow, 0).toString();

            // Panggil frame EditUser dengan ID tersebut
            EditProduk editForm = new EditProduk(id_barang);
            editForm.setVisible(true);
            editForm.setLocationRelativeTo(null); // tampil di tengah layar
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit terlebih dahulu!");
        }

    }//GEN-LAST:event_b_editActionPerformed

    private void B_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_hapusActionPerformed
        int baris = jTable1.getSelectedRow(); // tabelUser = JTable kamu
        if (baris != -1) { // Pastikan ada baris yang dipilih
            String id_barang = jTable1.getValueAt(baris, 0).toString(); // ambil id_user dari kolom pertama
            int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data dengan ID: " + id_barang + " ?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = koneksi.getConnection(); // panggil class koneksi kamu
                    String sql = "DELETE FROM barang WHERE id_barang = ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, id_barang);
                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus terlebih dahulu!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_B_hapusActionPerformed

    private void B_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RefreshActionPerformed
        loadDataProduk();
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RefreshActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

       filterData();
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Refresh;
    private javax.swing.JButton B_hapus;
    private javax.swing.JButton B_tambah;
    private javax.swing.JTextField Search;
    private javax.swing.JButton b_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
