
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }
    
    private LoginForm loginForm;

    public MenuAdmin(LoginForm loginForm) {
        this.loginForm = loginForm;
        initComponents();
        tampilkanDataAdmin();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // fullscreen
        setLocationRelativeTo(null);
    getProfil.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            // Buka Profil Admin
            ProfilForm profil = new ProfilForm();
            profil.setDataProfil(loginForm.getUsername(), loginForm.getUserRole(), loginForm.getUserId());
            profil.setVisible(true);
             // jika kamu ingin menutup menu admin sementara
    }
});

}
   
    
    private void tampilkanDataAdmin() {
        // Ambil data dari login form
        String username = loginForm.getUsername();
        String role = loginForm.getUserRole();
        int userId = loginForm.getUserId();
    
        // Cek di console dulu (debug)
        System.out.println("Admin yang login: " + username);
        System.out.println("Role: " + role);
        System.out.println("ID: " + userId);
    
        // Tampilkan di label profil
        getProfil.setText(username);
    }

        



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        getProfil = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        btnProduk = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(39, 174, 96));

        getProfil.setBackground(new java.awt.Color(0, 51, 255));
        getProfil.setForeground(new java.awt.Color(255, 255, 255));
        getProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-50.png"))); // NOI18N
        getProfil.setText("lblUser");

        btnUser.setText("Data User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnProduk.setText("Data Product");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        btnRiwayat.setText("Riwayat ");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnUser)
                .addGap(18, 18, 18)
                .addComponent(btnProduk)
                .addGap(18, 18, 18)
                .addComponent(btnRiwayat)
                .addGap(31, 31, 31)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(236, 240, 241));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(getProfil)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       // Tampilkan dialog konfirmasi
    int pilihan = JOptionPane.showConfirmDialog(
        this,                             // frame parent
        "Apakah Anda yakin ingin logout?", // pesan
        "Konfirmasi Logout",               // judul dialog
        JOptionPane.YES_NO_OPTION,         // opsi tombol: YES / NO
        JOptionPane.QUESTION_MESSAGE       // ikon dialog
    );

    // Jika pengguna memilih YES, jalankan logout
    if (pilihan == JOptionPane.YES_OPTION) {
        LoginForm login = new LoginForm();
        login.setLocationRelativeTo(null); // tampil di tengah layar
        login.setVisible(true);

        this.dispose(); // tutup MenuForm
    }
    // Jika NO, tidak terjadi apa-apa, MenuForm tetap terbuka
    }//GEN-LAST:event_logoutActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
// Hapus semua komponen yang sedang tampil di jPanel3
    jPanel3.removeAll();

    // Buat instance dari panel AdminMenu
    AdminMenu adminPanel = new AdminMenu();

    // Sesuaikan ukuran agar pas dengan jPanel3
    adminPanel.setSize(jPanel3.getSize());
    adminPanel.setVisible(true);

    // Tambahkan panel ke jPanel3
    jPanel3.add(adminPanel);

    // Refresh tampilannya supaya langsung kelihatan
    jPanel3.revalidate();
    jPanel3.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
       // Hapus semua komponen yang sedang tampil di jPanel3
    jPanel3.removeAll();

    // Buat instance dari panel AdminMenu
    DataProduk adminPanel = new DataProduk();

    // Sesuaikan ukuran agar pas dengan jPanel3
    adminPanel.setSize(jPanel3.getSize());
    adminPanel.setVisible(true);

    // Tambahkan panel ke jPanel3
    jPanel3.add(adminPanel);

    // Refresh tampilannya supaya langsung kelihatan
    jPanel3.revalidate();
    jPanel3.repaint();
       
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
    jPanel3.removeAll();

    // Buat instance dari panel AdminMenu
    RiwayatAdmin adminPanel = new RiwayatAdmin();

    // Sesuaikan ukuran agar pas dengan jPanel3
    adminPanel.setSize(jPanel3.getSize());
    adminPanel.setVisible(true);

    // Tambahkan panel ke jPanel3
    jPanel3.add(adminPanel);

    // Refresh tampilannya supaya langsung kelihatan
    jPanel3.revalidate();
    jPanel3.repaint();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel getProfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
