/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Riwayat extends javax.swing.JPanel {

    /**
     * Creates new form Riwayat
     */
    public Riwayat() {
        initComponents();
        loadDataRiwayat();
    }
    
    public void loadDataRiwayat() {
        DefaultTableModel model = (DefaultTableModel) tblRiwayat.getModel();
        model.setRowCount(0);

        try (Connection conn = koneksi.getConnection()) {
            String sql = "SELECT t.id_transaksi, t.tanggal_transaksi, " +
                         "IFNULL(p.nama, 'Umum') as pelanggan, " +
                         "IFNULL(u.username, 'Admin') as kasir, " +
                         "t.total_harga " +
                         "FROM transaksi t " +
                         "LEFT JOIN user u ON t.id_user = u.id_user " +
                         "LEFT JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan " +
                         "ORDER BY t.id_transaksi DESC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getString("tanggal_transaksi"),
                    rs.getString("pelanggan"),
                    rs.getString("kasir"),
                    rs.getDouble("total_harga")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat riwayat: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(39, 174, 96));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Riwayat Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Pelanggan", "Kasir", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRiwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRiwayat);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Detail Transaksi");

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Jumlah", "Harga Satuan", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRiwayatMouseClicked
        // TODO add your handling code here:
        int row = tblRiwayat.getSelectedRow();
        if (row != -1) {
            String idTrans = tblRiwayat.getValueAt(row, 0).toString();
            
            DefaultTableModel modelDetail = (DefaultTableModel) tblDetail.getModel();
            modelDetail.setRowCount(0);

            try (Connection conn = koneksi.getConnection()) {
                String sql = "SELECT b.nama_barang, dt.jumlah, dt.harga_satuan, dt.sub_total " +
                             "FROM detail_transaksi dt " +
                             "JOIN barang b ON dt.id_barang = b.id_barang " +
                             "WHERE dt.id_transaksi = ?";
                
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, idTrans);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    modelDetail.addRow(new Object[]{
                        rs.getString("nama_barang"),
                        rs.getInt("jumlah"),
                        rs.getDouble("harga_satuan"),
                        rs.getDouble("sub_total")
                    });
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat rincian: " + e.getMessage());
            }
        }
    
    }//GEN-LAST:event_tblRiwayatMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                             
    // Ambil input dari textfield dan simpan ke variabel 'input'
    String input = jTextField1.getText().trim();
    
    // Jika kolom kosong, tampilkan semua data
    if (input.isEmpty()) {
        loadDataRiwayat();
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblRiwayat.getModel();
    model.setRowCount(0); 

    try (Connection conn = koneksi.getConnection()) {
        String sql;
        PreparedStatement ps;

        // Cek apakah input adalah angka murni (untuk ID Transaksi)
        if (input.matches("\\d+")) { 
            // Query ID Transaksi harus SAMA PERSIS (=) agar tidak memunculkan semua data
            sql = "SELECT t.id_transaksi, t.tanggal_transaksi, " +
                  "IFNULL(p.nama, 'Umum') as pelanggan, " +
                  "IFNULL(u.username, 'Admin') as kasir, t.total_harga " +
                  "FROM transaksi t " +
                  "LEFT JOIN user u ON t.id_user = u.id_user " +
                  "LEFT JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan " +
                  "WHERE t.id_transaksi = ?"; 
            ps = conn.prepareStatement(sql);
            ps.setString(1, input);
        } else {
            // Jika mengandung karakter lain (seperti -), cari berdasarkan Tanggal
            sql = "SELECT t.id_transaksi, t.tanggal_transaksi, " +
                  "IFNULL(p.nama, 'Umum') as pelanggan, " +
                  "IFNULL(u.username, 'Admin') as kasir, t.total_harga " +
                  "FROM transaksi t " +
                  "LEFT JOIN user u ON t.id_user = u.id_user " +
                  "LEFT JOIN pelanggan p ON t.id_pelanggan = p.id_pelanggan " +
                  "WHERE t.tanggal_transaksi LIKE ? " +
                  "ORDER BY t.id_transaksi DESC";
            ps = conn.prepareStatement(sql);
            ps.setString(1, "%" + input + "%");
        }

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_transaksi"),
                rs.getString("tanggal_transaksi"),
                rs.getString("pelanggan"),
                rs.getString("kasir"),
                rs.getDouble("total_harga")
            });
        }
        
        // Jika tidak ada data yang ditemukan
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Data '" + input + "' tidak ditemukan.");
            loadDataRiwayat();
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Database: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(""); // Kosongkan kolom pencarian
    loadDataRiwayat();       // Muat semua riwayat
    
    // Bersihkan tabel detail di bawah
    DefaultTableModel modelDetail = (DefaultTableModel) tblDetail.getModel();
    modelDetail.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblRiwayat;
    // End of variables declaration//GEN-END:variables
}
